---
NONMEM_directory: /opt/nm742
NONMEM_version: '7.4'
PsN_version: 4.8.1
command_line: /usr/local/bin/execute run01.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 1
  compress: 0
  condition_number_limit: 1000
  correlation_limit: 0.85
  crash_restarts: 5
  degree: 0.1
  directory: /Users/jernest/Dropbox/PSPG_paperwork/Bootcamp_2020/bootcamp_2020/nm/modelfit_dir2/
  display_iterations: '1'
  handle_crashes: 1
  handle_msfo: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: '-99'
  model_subdir: 0
  near_bound_sign_digits: 2
  near_zero_boundary_limit: 0.01
  nice: 19
  nm_output: ext,cov,cor,coi,phi
  nm_version: default
  nmfe: '1'
  nmqual: 0
  nodes: 0
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 531081
  send_email: 0
  shrinkage: 0
  sign_digits_off_diagonals: 2
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/PsN_4_8_1/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: '5'
  tweak_inits: 1
  verbose: 0
  zip: 0
copied_files:
- run01.lst
- run01.ext
- run01.cov
- run01.cor
- run01.coi
- run01.phi
- sdtab01
- patab01
finish_time: 2020-08-12 15:32:36
model_files:
- /Users/jernest/Dropbox/PSPG_paperwork/Bootcamp_2020/bootcamp_2020/nm/run01.mod
start_time: 2020-08-12 15:32:28
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
